//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragWin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang___コピー {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang___コピー() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragWin.Properties.Lang - コピー", typeof(Lang___コピー).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Error adding to autorun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_error_autorun_add {
            get {
                return ResourceManager.GetString("Message.error.autorun.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error removing from autorun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_error_autorun_remove {
            get {
                return ResourceManager.GetString("Message.error.autorun.remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t get the executable&apos;s path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_error_executable {
            get {
                return ResourceManager.GetString("Message.error.executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error setting hookStruct に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_error_hookstruct {
            get {
                return ResourceManager.GetString("Message.error.hookstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error reading key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_error_read_key {
            get {
                return ResourceManager.GetString("Message.error.read.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error getting window handle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_error_window_handle {
            get {
                return ResourceManager.GetString("Message.error.window.handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error getting window handle&apos;s title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_error_window_title {
            get {
                return ResourceManager.GetString("Message.error.window.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start on login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_autorun {
            get {
                return ResourceManager.GetString("NotifyIcon.autorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for Updates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_check_update {
            get {
                return ResourceManager.GetString("NotifyIcon.check.update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_check_update_enable {
            get {
                return ResourceManager.GetString("NotifyIcon.check.update.enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_exit {
            get {
                return ResourceManager.GetString("NotifyIcon.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto FancyZones に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_fancyzones {
            get {
                return ResourceManager.GetString("NotifyIcon.fancyzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity scrolling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_opacity {
            get {
                return ResourceManager.GetString("NotifyIcon.opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen overflow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_overflow {
            get {
                return ResourceManager.GetString("NotifyIcon.overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize corners に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_resize {
            get {
                return ResourceManager.GetString("NotifyIcon.resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_scroll {
            get {
                return ResourceManager.GetString("NotifyIcon.scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wheel gesture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_wheel {
            get {
                return ResourceManager.GetString("NotifyIcon.wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New release! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toast_release_available {
            get {
                return ResourceManager.GetString("Toast.release.available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toast_release_close {
            get {
                return ResourceManager.GetString("Toast.release.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toast_release_install {
            get {
                return ResourceManager.GetString("Toast.release.install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no available update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toast_release_noavailable_body {
            get {
                return ResourceManager.GetString("Toast.release.noavailable.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are up to date! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toast_release_noavailable_header {
            get {
                return ResourceManager.GetString("Toast.release.noavailable.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Toast_update_failed {
            get {
                return ResourceManager.GetString("Toast.update.failed", resourceCulture);
            }
        }
    }
}
