//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구에 의해 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     이 파일을 변경하면 잘못된 동작이 발생할 수 있으며 코드가 재생성되면
//     손실될 수 있습니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragWin.Properties {
    using System;
    
    
    /// <summary>
    ///   현지화된 문자열 등을 조회하기 위해 강력하게 유형화된 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해
    // StrongTypeResourceBuilder 클래스에 의해 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여
    // ResGen을 다시 실행하거나 VS 프로젝트를 다시 빌드하세요.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragWin.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력하게 유형화된 리소스 클래스를 사용하는 모든 리소스 조회에 
        ///   대해 현재 스레드의 CurrentUICulture 프로퍼티를 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Error adding to autorun와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_error_autorun_add {
            get {
                return ResourceManager.GetString("Message.error.autorun.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error removing from autorun와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_error_autorun_remove {
            get {
                return ResourceManager.GetString("Message.error.autorun.remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t get the executable&apos;s path.과 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_error_executable {
            get {
                return ResourceManager.GetString("Message.error.executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error setting hookStruct와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_error_hookstruct {
            get {
                return ResourceManager.GetString("Message.error.hookstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   security settings or restrictions from anti-cheat or other software와 유사한 현지화된 문자열을 찾습니다..
        /// </summary>
        public static string Message_error_input {
            get {
                return ResourceManager.GetString("Message.error.input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error reading key와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_error_read_key {
            get {
                return ResourceManager.GetString("Message.error.read.key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error getting window handle와 유사한 로컬 문자열을 찾습니다.
        /// </summary>
        public static string Message_error_window_handle {
            get {
                return ResourceManager.GetString("Message.error.window.handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error getting window handle&apos;s title.와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_error_window_title {
            get {
                return ResourceManager.GetString("Message.error.window.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start on login과 유사한 로컬 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_autorun {
            get {
                return ResourceManager.GetString("NotifyIcon.autorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for Updates과 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_check_update {
            get {
                return ResourceManager.GetString("NotifyIcon.check.update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop Scrolling과 유사한 로컬 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_desktopScrolling {
            get {
                return ResourceManager.GetString("NotifyIcon.desktopScrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win + Scroll Wheel과 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_desktopScrolling_subText {
            get {
                return ResourceManager.GetString("NotifyIcon.desktopScrolling.subText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust the transparency of windows with a shortcut과 유사한 로컬 문자열을 찾습니다..
        /// </summary>
        public static string NotifyIcon_desktopScrolling_tooltip {
            get {
                return ResourceManager.GetString("NotifyIcon.desktopScrolling.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable과 유사한 현지화된 문자열을찾습니다.
        /// </summary>
        public static string NotifyIcon_enable {
            get {
                return ResourceManager.GetString("NotifyIcon.enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_exit {
            get {
                return ResourceManager.GetString("NotifyIcon.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto FancyZones과 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_fancyzones {
            get {
                return ResourceManager.GetString("NotifyIcon.fancyzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity scrolling과 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_opacity {
            get {
                return ResourceManager.GetString("NotifyIcon.opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lt + Scroll Wheel과 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_opacity_subText {
            get {
                return ResourceManager.GetString("NotifyIcon_opacity.subText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch between virtual desktops with a shortcut과 유사한 로컬 문자열을 찾습니다..
        /// </summary>
        public static string NotifyIcon_opacity_tooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_opacity.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen overflow와 유사한 로컬 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_overflow {
            get {
                return ResourceManager.GetString("NotifyIcon.overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restrict window drag to screen bounds과 유사한 현지화된 문자열을 찾습니다..
        /// </summary>
        public static string NotifyIcon_overflow_tooltip {
            get {
                return ResourceManager.GetString("NotifyIcon.overflow.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize corners와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_resize {
            get {
                return ResourceManager.GetString("NotifyIcon.resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll windows과 유사한 로컬 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_scroll {
            get {
                return ResourceManager.GetString("NotifyIcon.scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wheel down + Scrolling과 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_scroll_subText {
            get {
                return ResourceManager.GetString("NotifyIcon_scroll.subText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch between background windows한 로컬 문자열을 찾습니다..
        /// </summary>
        public static string NotifyIcon_scroll_tooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_scroll.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set window top.
        /// </summary>
        public static string NotifyIcon_settop {
            get {
                return ResourceManager.GetString("NotifyIcon.settop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wheel gesture와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_wheel {
            get {
                return ResourceManager.GetString("NotifyIcon.wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wheel down + L/R drag와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string NotifyIcon_wheel_subText {
            get {
                return ResourceManager.GetString("NotifyIcon_wheel.subText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch virtual desktops with the scroll wheel과 유사한 로컬 문자열을 찾습니다..
        /// </summary>
        public static string NotifyIcon_wheel_tooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_wheel.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New release!와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Toast_release_available {
            get {
                return ResourceManager.GetString("Toast.release.available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close와 유사한 로컬 문자열을 찾습니다.
        /// </summary>
        public static string Toast_release_close {
            get {
                return ResourceManager.GetString("Toast.release.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install와 유사한 로컬 문자열을 찾습니다.
        /// </summary>
        public static string Toast_release_install {
            get {
                return ResourceManager.GetString("Toast.release.install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no available update와 유사한 현지화된 문자열을 찾습니다..
        /// </summary>
        public static string Toast_release_noavailable_body {
            get {
                return ResourceManager.GetString("Toast.release.noavailable.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are up to date! 와 유사한 현지화된 문자열을 찾습니다.
        /// </summary>
        public static string Toast_release_noavailable_header {
            get {
                return ResourceManager.GetString("Toast.release.noavailable.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to update와 유사한 로컬 문자열을 찾습니다..
        /// </summary>
        public static string Toast_update_failed {
            get {
                return ResourceManager.GetString("Toast.update.failed", resourceCulture);
            }
        }
    }
}
